### ISSUE TITLE
Update iSponsorBlockTV to latest v2 release

### ISSUE THREAD

**Issue by iuri-gg** [bertybuttface/addons#14]
Could you please update iSponsorBlockTV addon to the latest v2 release?

**Comment by bertybuttface** [comment]
I'll take a look, is there a list of breaking changes somewhere?

**Comment by bertybuttface** [comment]
It is entirely untested but I have pushed a 2.0.0 release, give it a go if you are feeling brave.

**Comment by MaddoScientisto** [comment]
I just tried but it fails to install with this message:
Can't install ghcr.io/bertybuttface/aarch64-addon-isponsorblocktv:2.0.0: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=2.0.0&fromImage=ghcr.io%2Fbertybuttface%2Faarch64-addon-isponsorblocktv&platform=linux%2Farm64: Internal Server Error ("manifest unknown")

Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 3:57:26 PM (5 occurrences)
Last logged: 4:01:43 PM

```
Failed to to call /store/repositories - Cmd('git') failed due to: exit code(128) cmdline: git clone -v --recursive --depth=1 --shallow-submodules -- https://github.com/bertybuttface/addons/tree/main/isponsorblocktv /data/addons/git/c6aabcbc stderr: 'Cloning into '/data/addons/git/c6aabcbc'... fatal: repository 'https://github.com/bertybuttface/addons/tree/main/isponsorblocktv/' not found '
Failed to to call /store/repositories - https://github.com/bertybuttface/iSponsorBlockTV is not a valid add-on repository
Failed to to call /store/repositories - Cmd('git') failed due to: exit code(128) cmdline: git clone -v --recursive --depth=1 --shallow-submodules -- https://github.com/bertybuttface/addons/blob/main/isponsorblocktv /data/addons/git/f9a48b55 stderr: 'Cloning into '/data/addons/git/f9a48b55'... fatal: repository 'https://github.com/bertybuttface/addons/blob/main/isponsorblocktv/' not found '
Failed to to call /addons/932a64e5_isponsorblocktv/install - Can't install ghcr.io/bertybuttface/aarch64-addon-isponsorblocktv:2.0.0: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=2.0.0&fromImage=ghcr.io%2Fbertybuttface%2Faarch64-addon-isponsorblocktv&platform=linux%2Farm64: Internal Server Error ("manifest unknown")
```

**Comment by bertybuttface** [comment]
Yeah thats on me, I was maintaining a fork so breaking changes wouldn't hit this addon. I've removed the fork for now and I'll push a 2.0.1 release.

**Comment by bertybuttface** [comment]
Upstream removed the ability to specify a config file (cheers for that), I've tried using a symlink for now but not tested.

2.0.2 is building now.

**Comment by bertybuttface** [comment]
Ok that works but it doesn't survive a reboot. 2.0.3 is building now.

**Comment by dmunozv04** [comment]
> Upstream removed the ability to specify a config file (cheers for that), I've tried using a symlink for now but not tested.

Sorry about that, it was done to support having multiple files in the future, and launching with docker easier

**Comment by bertybuttface** [comment]
No worries I appreciate your hard work.
