### ISSUE TITLE
Update iSponsorBlockTV to latest 

### ISSUE THREAD

**Issue by iuri-gg** [bertybuttface/addons#21]
Hey there. Is it possible to get updated iSponsorBlockTV from couple weeks ago?

**Comment by bertybuttface** [comment]
Sure, I didn't see anything relevant in the release notes so didn't bother updating. Is there a feature or bug fix you are after in particular?

**Comment by iuri-gg** [comment]
Thanks. I’m interested in the “Fix for the ad skips” - it’s been buggy for me. I was hoping it would be better.

**Comment by bertybuttface** [comment]
I suspect you are encountering https://github.com/dmunozv04/iSponsorBlockTV/issues/119 as both the code author and myself have been experiencing. Sadly there is no fix for this yet.

I've updated to the latest upstream release, it looks like there may have been some config file changes so let me know if you experience any issues with that and I'll look into it. Cheers.

**Comment by dmunozv04** [comment]
YouTube ad skips (not segments from sponsorblock) were indeed improved/fixed in v2.0.4 and I’ll make another change soon(ish) to make them work better

**Comment by bertybuttface** [comment]
Fantastic cheers @dmunozv04
