### ISSUE TITLE
Add-on fails to start; can't open file '/usr/app/main.py'

### ISSUE THREAD

**Issue by dstockhammer** [bertybuttface/addons#22]
After upgrading to version **2.0.8** (latest as of time of writing), the container no longer starts. It looks like the problem is `python3: can't open file '/usr/app/main.py': [Errno 2] No such file or directory`. Here are the full logs:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun isponsorblocktv (no readiness notification)
s6-rc: info: service legacy-services successfully started
[10:08:24] INFO: Starting...
python3: can't open file '/usr/app/main.py': [Errno 2] No such file or directory
[09:08:25] WARNING: Halt add-on with exit code 2
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by Sxkre** [comment]
Im getting the exact same error. Even a fresh install keeps getting message “ can't open file '/usr/app/main.py”

**Comment by bertybuttface** [comment]
Yup I can reproduce this here, there are some changes to the upstream project structure that likely caused this (and the fact I pushed a release without testing it, apologies for that I was attempting to help another user with a different issue).

Changes came in from this commit: https://github.com/dmunozv04/iSponsorBlockTV/commit/5a5ebcfeb760743bcb79f685b388c749557d82ae

**Comment by bertybuttface** [comment]
Simple problem, simple fix. Hopefully this works now in 2.0.9 Please let me know if you encounter any more issues.

I'll try and be a bit more careful when rolling a release.

**Comment by Sxkre** [comment]
> Simple problem, simple fix. Hopefully this works now in 2.0.9 Please let me know if you encounter any more issues.
> 
> I'll try and be a bit more careful when rolling a release.

Fixed! Thank you so much for the quick reply. LOVE this addon!
