### ISSUE TITLE
Event Not Pulling from Frigate

### ISSUE THREAD

**Issue by alohacorey** [bertybuttface/addons#27]
The bird detection is working within Frigate and triggering the event for WhosAtMyFeeder but never displays the event.

In the log I get:
Getting image for event: 1716174400.687371-5jvl32
Here's the URL: http://homeassistant.local:5000/api/events/1716174400.687371-5jvl32/snapshot.jpg

That URL however never loads and appears to be invalid. When I look at the snapshots within Frigate it seems like it is formatted differently. Here is how the same event snapshot is formatted in Frigate:
http://homeassistant.local:8123/api/hassio_ingress/fKLDvjoKaf4-Q-hrhFaR5QOhM2uhLORPqLcOA8vyEt8/api/events/1716174400.687371-5jvl32/snapshot.jpg?bbox=1

Any ideas?

**Comment by bertybuttface** [comment]
I'm not currently supporting that addon as it is not being supported by its original author. Sorry.
