### ISSUE TITLE
iSponsorblockTV won't start after latest update

### ISSUE THREAD

**Issue by dd310** [bertybuttface/addons#37]
Add-on halts at start after 2.1.1 update

`
s6-rc: info: service s6rc-oneshot-runner: starting s6-rc: info: service s6rc-oneshot-runner successfully started s6-rc: info: service fix-attrs: starting s6-rc: info: service fix-attrs successfully started s6-rc: info: service legacy-cont-init: starting s6-rc: info: service legacy-cont-init successfully started s6-rc: info: service legacy-services: starting services-up: info: copying legacy longrun isponsorblocktv (no readiness notification) [02:27:03] INFO: Starting... s6-rc: info: service legacy-services successfully started Usage: main.pyc [OPTIONS] COMMAND [ARGS]... Try 'main.pyc --help' for help ╭─ Error ──────────────────────────────────────────────────────────────────────╮ │ No such option: --data-dir Did you mean --data? │ ╰──────────────────────────────────────────────────────────────────────────────╯ [00:27:04] WARNING: Halt add-on with exit code 2
`

**Comment by bertybuttface** [comment]
Fixed by 2.1.2 https://github.com/bertybuttface/addons/pull/38 once it is finished building.
