### ISSUE TITLE
Not skipping sponsor

### ISSUE THREAD

**Issue by mandrean** [bertybuttface/addons#39]
I migrated from a previously working https://github.com/dmunozv04/iSponsorBlockTV (using `podman`) to this HA addon, and it doesn't skip the ads anymore?

rpi5, HA 13.2

`configuration.yaml`:

```
apikey: <MY_API_KEY>
devices:
  - screen_id: <MY_SCREEN_ID>
    name: YouTube on TV
channel_whitelist: []
skip_categories:
  - sponsor
  - exclusive_access
  - interaction
  - filler
  - preview
  - poi_highlight
  - music_offtopic
  - outro
  - intro
  - selfpromo
skip_count_tracking: false
mute_ads: true
skip_ads: true
auto_play: false
```

Logs:

```
[04:50:40] INFO: Starting...
s6-rc: info: service legacy-services successfully started
2024-11-10 04:50:41,608 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Starting device
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f7cb7df40>
2024-11-10 04:50:41,680 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Refreshed auth, lounge id token <TOKEN>
2024-11-10 04:50:41,961 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Connected to device YouTube on TV (YouTube on TV)
2024-11-10 04:50:41,961 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Subscribing to lounge
2024-11-10 04:50:41,962 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Subscribing to lounge id <ID>
2024-11-10 04:51:07,299 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Playing video y-jy_1-65q4 with 2 segments
2024-11-10 04:51:08,700 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Ad has ended, unmuting
2024-11-10 04:51:08,702 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Playing video y-jy_1-65q4 with 2 segments
2024-11-10 04:51:11,030 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Playing video y-jy_1-65q4 with 2 segments
2024-11-10 04:51:13,069 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Playing video y-jy_1-65q4 with 2 segments
2024-11-10 04:51:15,341 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Playing video y-jy_1-65q4 with 2 segments
2024-11-10 04:51:45,424 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Playing video y-jy_1-65q4 with 2 segments
2024-11-10 04:51:50,946 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Playing video y-jy_1-65q4 with 2 segments
2024-11-10 04:51:53,143 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Playing video y-jy_1-65q4 with 2 segments
```

Watching this video: https://www.youtube.com/watch?v=y-jy_1-65q4, at approx 1m34s it should skip the ad, but it doesn't. The logs seem fine though...

**Comment by mandrean** [comment]
I also noticed that the latest upstream version is `v2.2.1`, but this addon presumably vendors `v2.1.2`. Can you bump that?

**Comment by bertybuttface** [comment]
I will update later but I use this code myself and it works fine. From the logs it looks like its muting not skipping.

Try setting mute_ads to false.

**Comment by mandrean** [comment]
>I use this code myself and it works fine.

"It works on my machine"

>Try setting mute_ads to false.

1. I tested it with `mute_ads: false`, no difference.
2. The same config works as expected on vanilla `iSponsorBlockTV`.

Logs with `mute_ads: false`, yet ad isn't skipped for https://www.youtube.com/watch?v=y-jy_1-65q4:

> 2024-11-10 15:10:06,419 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Refreshed auth, lounge id token <TOKEN>
> 2024-11-10 15:10:06,716 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Connected to device None (YouTube on TV)
> 2024-11-10 15:10:06,717 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Subscribing to lounge
> 2024-11-10 15:10:06,718 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Subscribing to lounge id <TOKEN>
> 2024-11-10 15:11:23,896 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Playing video y-jy_1-65q4 with 2 segments
> 2024-11-10 15:11:25,536 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Playing video y-jy_1-65q4 with 2 segments
> 2024-11-10 15:11:33,155 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Playing video y-jy_1-65q4 with 2 segments

**Comment by bertybuttface** [comment]
Fix it yourself, code is open source, I have no desire to help someone that is rude.

**Comment by mandrean** [comment]
Where is the rudeness you're talking about?

**Comment by bertybuttface** [comment]
"works on my computer"

No need for it, I was willing to spend some of my weekend helping you before that little barb. Happy to accept a PR.

**Comment by mandrean** [comment]
Yeah it's not rude to point out the [It Works On My Machine](https://www.reddit.com/r/ProgrammerHumor/comments/70we66/it_works_on_my_machine/) trope, it's just humor. There can be many reasons for that being the case.

**Comment by bertybuttface** [comment]
> but this addon presumably vendors `v2.1.2`. Can you bump that?

Addon is already up to date, presumption that the version numbers match between addon and main package is incorrect.

**Comment by bertybuttface** [comment]
I was simply reporting that this code is in daily use by myself, your response was dismissive. I replied to your issue same day wanting to try and help you but you respond by claiming my response was a trope? Help yourself.

**Comment by mandrean** [comment]
>Addon is already up to date, presumption that the version numbers match between addon and main package is incorrect.

I don't think my assumption is incorrect, no. 

The most recent `ghcr.io/bertybuttface/{arch}-addon-isponsorblocktv` images (which is what HA uses, not the git repository directly) were built/pushed on March 31:

https://github.com/bertybuttface?tab=packages&tab=packages&q=isponsorblocktv

![Skärmavbild 2024-11-10 kl  15 42 35](https://github.com/user-attachments/assets/4c6ed505-a5cb-4655-8621-74d950f5ac67)

But the latest version (`v2.2.1`) upstream was published on September 18. In fact, March 31 probably puts it at `v2.0.6`, not even `v2.1.2` as is [indicated by the manifest](https://github.com/bertybuttface/addons/blob/main/isponsorblocktv/config.yaml#L3). 

![Skärmavbild 2024-11-10 kl  15 51 44](https://github.com/user-attachments/assets/336706ce-888d-4920-bd5c-915a07557df3)

**Comment by bertybuttface** [comment]
<img width="618" alt="Screenshot 2024-11-10 at 14 52 07" src="https://github.com/user-attachments/assets/d8c4b9ff-7b6d-4ec5-b882-4d6e1ac79c50">

You are looking in the wrong place.

Also as previously stated the version numbers of the package and this addon are not in sync. The fact they are close to each other is purely coincidental.

**Comment by bertybuttface** [comment]
You are wasting your time and my time, sort it out.
