### ISSUE TITLE
Not skipping sponsor, part 2 - workaround

### ISSUE THREAD

**Issue by mandrean** [bertybuttface/addons#40]
For any other users out there running into the same issue as in #39, here's a workaround that immediately worked for me. Zero frustration. ❤️

**Hardware:** Raspberry Pi 5 running HassOS 13.2 + YouTube on Apple TV 4K (3rd gen)

1. Uninstall this `iSponsorBlockTV` HA addon
2. Enable HA host SSH access: https://developers.home-assistant.io/docs/operating-system/debugging/
3. `mkdir -p /mnt/data/containers/isponsorblocktv && cd /mnt/data/containers/isponsorblocktv`
4. `vi config.json`, paste in your `iSponsorBlockTV` JSON config. `:wq` + `[ENTER]` to save+close.
5. 
```sh
docker run -d \
    --name iSponsorBlockTV \
    --restart=unless-stopped \
    -v /mnt/data/containers/isponsorblocktv:/app/data \
    ghcr.io/dmunozv04/isponsorblocktv
```

Done! Verify it started successfully with: `docker logs iSponsorBlockTV`

Logs while watching https://www.youtube.com/watch?v=y-jy_1-65q4 now skip the sponsor segment as intended:

> 2024-11-10 16:02:36,325 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Starting device
> 2024-11-10 16:02:36,406 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Refreshed auth, lounge id token <TOKEN>
> 2024-11-10 16:02:56,954 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Connected to device YouTube on TV
> 2024-11-10 16:02:56,954 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Subscribing to lounge
> 2024-11-10 16:02:56,957 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Subscribing to lounge id <TOKEN>
> 2024-11-10 16:03:32,101 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Playing video y-jy_1-65q4 with 2 segments
> 2024-11-10 16:03:38,536 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Playing video y-jy_1-65q4 with 2 segments
> 2024-11-10 16:03:40,172 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Playing video y-jy_1-65q4 with 2 segments
> 2024-11-10 16:03:48,090 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Skipping segment: seeking to 183.61877
> 2024-11-10 16:03:48,594 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Playing video y-jy_1-65q4 with 2 segments
> 2024-11-10 16:04:01,682 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Playing video y-jy_1-65q4 with 2 segments
> 2024-11-10 16:04:03,382 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Playing video y-jy_1-65q4 with 2 segments
> 2024-11-10 16:04:03,564 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Skipping segment: seeking to 183.61877
> 2024-11-10 16:04:04,061 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Playing video y-jy_1-65q4 with 2 segments
> 2024-11-10 16:07:46,588 - iSponsorBlockTV-<MY_SCREEN_ID> - INFO - Subscribe completed, status 200 OK

Cheers everyone!

**Comment by bertybuttface** [comment]
Alternatively you can just configure the addon properly like everyone else using this addon. All you have done here is show that the issue was with your config.
